---
- name: Download Nexus
  ansible.builtin.unarchive:
    src: "{{ nexus_download_url }}"
    dest: "{{ nexus_install_tmp_base_dir }}"
    remote_src: yes
    creates: "{{ nexus_service_file_path }}"

- name: Install Nexus
  ansible.builtin.shell: "shopt -s dotglob && mv {{ nexus_install_tmp_dir }}/* {{ nexus_install_dir }} && shopt -u dotglob"
  ansible.builtin.args:
    executable: /bin/bash
    creates: "{{ nexus_install_dir }}/bin"
    removes: "{{ nexus_install_tmp_dir }}"

- name: Install Nexus Data
  ansible.builtin.command: "mv {{ nexus_install_tmp_data_dir }} {{ nexus_data_dir }}"
  ansible.builtin.args:
    creates: "{{ nexus_data_dir }}"
    removes: "{{ nexus_install_tmp_data_dir }}"

- name: Change file permission of Nexus installation directory
  ansible.builtin.file:
    dest: "{{ nexus_install_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes

- name: Change file permission of Nexus Data directory
  ansible.builtin.file:
    dest: "{{ nexus_data_dir }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    recurse: yes
